---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJmcmVkYmVsb3R0ZSIsInBhc3N3b3JkIjoiZTU0MGFiN2RhMzQ5MzA1OTQzMzc2ZWI5ZGQyYTU1NDgwOWMxNGY5NCIsImF1dGgiOiJabkpsWkdKbGJHOTBkR1U2WlRVME1HRmlOMlJoTXpRNU16QTFPVFF6TXpjMlpXSTVaR1F5WVRVMU5EZ3dPV014TkdZNU5BPT0ifX19
kind: Secret
metadata:
  name: github
type: kubernetes.io/dockerconfigjson
